# .gitlab-ci.yml (snippet)
image: docker:27.3.1

variables:
  DOCKER_BUILDKIT: "1"
  DOCKERFILE_DIR: "src/cro_rmi_improvement_feature/network_analyzer"
  ECR_REGISTRY: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"

stages: [build]

before_script:
  - apk add --no-cache aws-cli docker-cli jq
  - aws --version
  - docker --version
  - pwd
  - echo "CI_PROJECT_DIR=$CI_PROJECT_DIR"
  - ls -la
  - ls -la src || true
  - ls -la src/cro_rmi_improvement_feature || true
  - ls -la src/cro_rmi_improvement_feature/network_analyzer || true
  - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$ECR_REGISTRY"
  
build-and-push:
  stage: build
  tags: ["docker"]
  script:
    - export IMAGE="$ECR_REGISTRY/$ECR_REPOSITORY"
    - export TAG="${CI_COMMIT_SHORT_SHA}"
    - docker build -t "$IMAGE:$TAG" -f "$CI_PROJECT_DIR/$DOCKERFILE_DIR/Dockerfile.GitLab" --build-context dataset="/home/thanatorn/coding/cro_rmi_improvement_feature/src/cro_rmi_improvement_feature/network_analyzer/data" "$CI_PROJECT_DIR/$DOCKERFILE_DIR"
    - docker push "$IMAGE:$TAG"
