image: docker:28-dind

services:
    - name: docker:28-dind

default:
  tags:
    - vision_vm

variables:
  DOCKERFILE_DIR: "src/cro_rmi_improvement_feature/network_analyzer"
  ECR_REGISTRY: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"

stages:
    - exploration
    - build_push

exploration:
    stage: exploration
    before_script:
        - apk add --no-cache tree
    script:
        - cd /mnt/data
        - ls -la
        - echo "=== Directory Tree Structure ==="
        - echo "=== Contents of /mnt/data ===" 
        - tree .

build_and_push:
    stage: build_push
    before_script:
        - apk add --no-cache aws-cli docker-cli jq
        - aws --version
        - docker --version
        - pwd
        - echo "$CI_PROJECT_DIR"
        - cd "$CI_PROJECT_DIR/$DOCKERFILE_DIR
        - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$ECR_REGISTRY"
    script:
        - docker version
